### PR TITLE
small tweaks to optimization and the config screen

### PR DESCRIPTION
**Pull request by poqbox**
I made some minor optimization changes. It won't make a noticeable difference, but here it is anyways.
I also saw that one of the config options was missing a tooltip, so I added a tooltip to it.

### CODE REVIEW

**Comment by poqli** [comment]
My last commit (https://github.com/Provismet/Tooltip-Scroll-Fabric/pull/24/commits/c57ccc805077796651bd2ec4e86c8b6f87e7977b) could use some extra review.

I removed the check for a non-empty `components` because the method that applyTracker() was being injected into already has a check for it. To do so, I had to change where it is being injected into. It's still injecting into the same method, just further into it instead of at the start.

The tooltip scrolling still works, I'm just not sure if it breaks some intended behavior that I'm not aware of.

**Comment by poqli** [comment]
My last commit (https://github.com/Provismet/Tooltip-Scroll-Fabric/pull/24/commits/ba774526a59a4f3f0b4f9c3968dfdb1aea106a09) could use some extra review.

I removed the check for a non-empty components because the method that applyTracker() was being injected into already has a check for it. To do so, I had to change where it is being injected into. It's still injecting into the same method, just further into it instead of at the start.

The tooltip scrolling still works, I'm just not sure if it breaks some intended behavior that I'm not aware of.

**Comment by poqbox** [comment]
My last commit (https://github.com/Provismet/Tooltip-Scroll-Fabric/pull/24/commits/ba774526a59a4f3f0b4f9c3968dfdb1aea106a09) could use some extra review.

I removed the check for a non-empty components because the method that applyTracker() was being injected into already has a check for it. To do so, I had to change where it is being injected into. It's still injecting into the same method, just further into it instead of at the start.

The tooltip scrolling still works, I'm just not sure if it breaks some intended behavior that I'm not aware of.

**Comment by Provismet** [comment]
> I removed the check for a non-empty components because the method that applyTracker() was being injected into already has a check for it. To do so, I had to change where it is being injected into. It's still injecting into the same method, just further into it instead of at the start.

Good catch on that one, it was originally made that way because of how _odd_ the `drawTooltip` method used to be. I imagine it changed in 1.20 or 1.21 in a way that didn't break the mod, because otherwise I would have checked.

If I remember correctly, the method originally didn't have a proper check for empty tooltips. It was an issue because certain menus would call `drawTooltip` repeatedly with empty tooltips (the options menu was pretty bad for this) and some would even alternate between valid calls and empty ones.

**Comment by Provismet** [comment]
Also, could you pull the upstream changes into your PR branch? Just to smoothen out the conflicts before I merge.

**Comment by poqbox** [comment]
I believe this should fix the conflicts.

**Review by Provismet — APPROVED** [review]

**Pull request merged**
